- name: Ensure beszel-agent container is running
  community.docker.docker_container:
    name: beszel-agent
    image: henrygd/beszel-agent:latest
    state: started
    restart_policy: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env:
      KEY: "{{ beszel_ssh_key }}"
      LISTEN: "45876"

