- name: Pull OpenObserve image
  docker_image:
    name: public.ecr.aws/zinclabs/openobserve
    tag: v0.10.9
    source: pull

- name: Create OpenObserve log directory
  file:
    path: /var/log/openobserve
    state: directory
    mode: '0755'

- name: Create logrotate configuration
  copy:
    dest: /etc/logrotate.d/openobserve
    content: |
      /var/log/openobserve/*.log {
        daily
        rotate 14
        missingok
        compress
        delaycompress
        notifempty
        create 0640 root adm
      }

- name: Run OpenObserve container
  docker_container:
    name: openobserve
    image: public.ecr.aws/zinclabs/openobserve:v0.10.9
    restart_policy: unless-stopped
    ports:
      - "5080:5080"
    env:
      ZO_ROOT_USER_EMAIL: "{{root_email}}"
      ZO_ROOT_USER_PASSWORD: "{{root_password}}"
      ZO_META_STORE: postgres
      ZO_POSTGRES_DSN: postgres://openobserve:"{{postgres_password}}"@postgres:5432/openobserve
      ZO_S3_PROVIDER: minio
      ZO_S3_SERVER_URL: "{{s3_address}}"
      ZO_S3_REGION_NAME: us-east-1
      ZO_S3_BUCKET_NAME: openobserve
      ZO_S3_ACCESS_KEY: "{{s3_access_key}}"
      ZO_S3_SECRET_KEY: "{{s3_secret_key}}"
    volumes:
      - /var/log/openobserve:/var/log/openobserve
    networks:
      - openobserve_network
