- name: Update apt package index
  ansible.builtin.apt:
    update_cache: yes

- name: Create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download and add Docker GPG key
  ansible.builtin.shell: |
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: Get system architecture
  ansible.builtin.command: dpkg --print-architecture
  register: system_arch
  changed_when: false

- name: Get Debian codename
  ansible.builtin.command: lsb_release -cs
  register: debian_codename
  changed_when: false

- name: Remove any existing Docker repository files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/sources.list.d/docker.list
    - /etc/apt/sources.list.d/docker.sources

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: >
      deb [arch={{ system_arch.stdout }} signed-by=/etc/apt/keyrings/docker.gpg]
      https://download.docker.com/linux/debian {{ debian_codename.stdout }} stable
    state: present
    filename: docker

- name: Update apt package index after adding Docker repo
  ansible.builtin.apt:
    update_cache: yes

- name: Install Docker engine and CLI tools
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Create docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: Ensure Docker service is started and enabled
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Verify Docker installation
  ansible.builtin.command: docker --version
  register: docker_version
  changed_when: false

- name: Display Docker version
  ansible.builtin.debug:
    msg: "Docker installed successfully: {{ docker_version.stdout }}"

- name: Create network for openobserve and postgres
  docker_network:
    name: openobserve_network
