- name: System Setup
  hosts: openobserve-root
  become: true
  roles:
    - system_prep

- name: Install Docker
  hosts: openobserve-dev
  become: true
  roles:
    - docker_install

- name: Install and configure postgres
  hosts: openobserve-dev
  become: true
  roles:
    - postgres_docker

- name: Install and configure openobserve
  hosts: openobserve-dev
  become: true
  roles:
    - openobserve_docker

- name: Setup Beszel agent
  hosts: openobserve-dev
  become: true
  vars:
    beszel_ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAtNz9vj2a4dh+Bs4D+v6Ov2QXiZIS8TMNlnObYmlaNS"
  roles:
    - beszel_docker
